# Defaults for image training.

image_size: 256
num_channels: 128
num_res_blocks: 3
channel_mult: ""
learn_sigma: True
class_cond: False
use_checkpoint: False
#attention_resolutions: 16
num_heads: 4
num_head_channels: -1
num_heads_upsample: -1
use_scale_shift_norm: True
dropout: 0.1
resblock_updown: False
use_fp16: False
use_new_attention_order: False

model_path: /storage/arunima/Arunima/checkpoint/hcp_checkpoint/ema_0.9999_200000.pt

