conditioning:
  method: ps
  params:
    scale: 0.1

data:
  name: ffhq
  root: /srv/Data/playground_data/ffhq #### added this too
  brats_path: /srv/Data/playground_data/brats/brats_training_data/data_raw
  h5_path: /srv/Data/playground_data/brats/h5_t1_t2

measurement:
  operator:
    name: motion_blur
    kernel_size: 31
    intensity: 0.4

  noise: 
    name: gaussian
    sigma: 0.05
