conditioning:
  method: ps
  params:
    scale: 1

data:

#   data_path: /storage/Arunima/dataset/BRATS2020/brats_validation_data/MICCAI_BraTS2020_ValidationData
  h5_path: /storage/arunima/Arunima/dataset/hcp_h5
  
  mode: test

measurement:
  operator:
    name: motion_artifact
    xy_max: 1 #2
    theta_max: 0
    num_motions: 5 #5
    center_fractions: 0.1
    wave_num: 0 #4
    motion_type: randomize_harmonic
    noise_lvl: 0

  noise: 
    name: gaussian # changed the implementation to rician.
    sigma: 0.00
